import type { Passenger, Trip } from './types';

// Datos estáticos de prueba para maquetar la Fase 1.
// En la Fase 2 esto se reemplaza por un fetch a Supabase.

export const VIAJE_MOCK: Trip = {
  id_viaje: 'mock-pico-naiguata',
  destino: 'Pico Naiguatá',
  fecha_salida: '2026-09-14',
  puestos_totales: 40,
};

export const PASAJEROS_MOCK: Passenger[] = [
  {
    id_viajero: 'm-01',
    id_viaje: VIAJE_MOCK.id_viaje,
    nombre_completo: 'Ana Pérez',
    grupo_origen: 'Grupo 1',
    zona_recogida: 'Santa Rosa',
    metodo_pago: 'Pago Móvil',
    estado_pago: 'Completo',
    monto_abonado: 25,
    monto_pendiente: 0,
  },
  {
    id_viajero: 'm-02',
    id_viaje: VIAJE_MOCK.id_viaje,
    nombre_completo: 'Luis Gómez',
    grupo_origen: 'Grupo 2',
    zona_recogida: 'El Cafetal',
    metodo_pago: 'Efectivo',
    estado_pago: 'Abonado',
    monto_abonado: 10,
    monto_pendiente: 15,
  },
  {
    id_viajero: 'm-03',
    id_viaje: VIAJE_MOCK.id_viaje,
    nombre_completo: 'María Rodríguez',
    grupo_origen: 'Grupo 1',
    zona_recogida: 'Santa Rosa',
    metodo_pago: 'Pago Móvil',
    estado_pago: 'Pendiente',
    monto_abonado: 0,
    monto_pendiente: 25,
  },
  {
    id_viajero: 'm-04',
    id_viaje: VIAJE_MOCK.id_viaje,
    nombre_completo: 'Carlos Díaz',
    grupo_origen: 'Grupo 3',
    zona_recogida: 'Chacao',
    metodo_pago: 'Efectivo',
    estado_pago: 'Completo',
    monto_abonado: 25,
    monto_pendiente: 0,
  },
  {
    id_viajero: 'm-05',
    id_viaje: VIAJE_MOCK.id_viaje,
    nombre_completo: 'Elena Torres',
    grupo_origen: 'Grupo 2',
    zona_recogida: 'El Cafetal',
    metodo_pago: 'Pago Móvil',
    estado_pago: 'Abonado',
    monto_abonado: 20,
    monto_pendiente: 5,
  },
  {
    id_viajero: 'm-06',
    id_viaje: VIAJE_MOCK.id_viaje,
    nombre_completo: 'Jorge Blanco',
    grupo_origen: 'Grupo 3',
    zona_recogida: 'Los Palos Grandes',
    metodo_pago: 'Efectivo',
    estado_pago: 'Pendiente',
    monto_abonado: 0,
    monto_pendiente: 25,
  },
  {
    id_viajero: 'm-07',
    id_viaje: VIAJE_MOCK.id_viaje,
    nombre_completo: 'Patricia León',
    grupo_origen: 'Grupo 1',
    zona_recogida: 'Chacao',
    metodo_pago: 'Pago Móvil',
    estado_pago: 'Completo',
    monto_abonado: 25,
    monto_pendiente: 0,
  },
];
